---
#configure cron job
##0     8,18,20   1-5    1,3,4,6   2                  /usr/sbin/vgs>/tmp/vgs.out
#Mins   Hours     Date   Month     Daysofthe week     /path/to/command
#
- name: Demonstrate cron module to schedule a job
  hosts: localhost
  become: yes
  tasks:
   - name: configure cron job
     cron:
      name: "My Cron"
      state: absent
...
#End