---
- name: Call the script from shell module
  hosts: [192.168.1.55,192.168.1.59]
  become: true 
  tasks:
  - name: Push script to remote server
    copy:
     src: myscript.sh
     dest: /tmp/myscript.sh
     mode: '0755'
  - name: Shell Module to execute a script
    shell: /tmp/myscript.sh
...
#End