---
- name: Demonstrate when condition
  hosts: web
  become: true
  remote_user: ansible
  tasks:
   - name: Task to install package
     yum:
      name: httpd
      state: latest
     when: ansible_as_family == "RedhHat" or ansible_os_family == ""centos"
   - name: Task to install package
     apt:
      name: apache2
      state: latest
     when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"  
...