<<<<<<< HEAD
#we are in main branch
=======
>>>>>>> 89b41af366173d84733fd8a302bd7d68862e054b
---
- name: Play to Install httpd package
  hosts: sapadm
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Task to copy my repo file to remote server 
      copy:
        src: /etc/yum.repos.d/RHEL95.repo
        dest: /etc/yum.repos.d/rhel95.repo

    - name: Task to install httpd package
      yum:
        name: httpd
        state: latest

    - name: Task to add the port in the firewall
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Create index.html 
      copy:
        dest: /var/www/html/index.html
        content: "<html><h1><center>This is built by ansible</center></h1></html>"
        mode: '0644'

    - name: Start http service
      service:
        name: httpd
        state: started
        enabled: yes
...
