--- 
- name: play to demonstrate stat module
  hosts: localhost 
  become: true 
  vars:
   fname: /etc/passwd
  tasks: 
  - name: check if the file exists
    stat: 
     path: "{{fname}}"
    register: out
  - name: print if the file exists
    debug:
     msg: "File {{fname}} exists"
    when: out.stat.exists
  - name: print if the file does not exists
    debug:
     msg: "File {{fname}} exists"
    when: not out.stat.exists 
... 
#End 