---
- name: play to demonstration loop with_dict. Iterate over dictionary.
  hosts: localhost
  become: true
  tasks:
   - name: print dict 
     debug: 
      msg: "{{item.key}} assigned with UID: {{item.value.uid}} and its shell is: {{item.value.shell}}"
     with_dict:
      harika:
       uid: 5001
       shell: /bin/bash
      mounika:
       uid: 5002
       shell: /bin/ksh
... 
#End 