---
- name: Play to demonstrate archive
  hosts: [192.168.1.31]
  become: true
  become_user: root
  gather_facts: false
  tasks:
   - name: Task to archive reomote server /etc
     archive: 
      path: /etc
      dest: /tmp/etc_archive.tar.gz
      format: gz
      owner: ansible
      group: ansible
      mode: 0600
...