---
- name: create a user with given variables
  hosts: localhost
  become: yes
  remote_user: ansible
  become_user: root
  vars:
   grpname: datalake
   usrname: db101
   usr_pas: abc@123
  tasks:
   - name: create a group {{grpname}} which will e used as asecondary group for the created user
     group:
      name: "{{grpname}}"
      state: present
   - name: create {{usrname}} with secondary group {{grpname}}
     user:
      name: "{{usrname}}"
      password: "{{usr_pas|password_hash('sha512')}}"
      update_password: on_create
      groups: "{{grpname}}"
      state: present
...