#we are in main branch
---
- name: Demonstrate lineinfile - example2
  hosts: localhost
  become: true

  tasks:
    - name: Replace the PermitRootLogin line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Restart the sshd service
      service:
        name: sshd
        state: restarted
...
# End
