--- 
- name: play to demonstarate debug 
  hosts: localhost 
  become: true 
  tasks: 
   - name: debug module 
     debug: 
      msg: "Did you changed ??"
     changed_when: true  #this make change: true 
     notify: one_more
   - name: debug module 
     debug:
      msg: " Not sure if I am changed ??"
     changed_when: true   #this make change: true
     notify: print_me
   - name: Flush handlers
     meta: flush_handlers
   - name: debug module - again
     debug: 
      msg: " once gain ??"
     changed_when: true 
     notify: print_me
    #This is second time you are notifying the print_me handler 
  handlers:
   - name: print_me
     debug: 
      msg: "I am in handler"
   - name: one_more 
     debug:
      msg: "Yes.. I am in handler"
... 