---
- name: Call the script from the shell module
  hosts: [192.168.1.55,192.168.1.59]
  become: true
  tasks:
  - name: Script Module to execute on a remote server 
    script: /home/ansible/playbook/printdf.sh
...
#Please note that the script module copies a local script file from control node
#to remote host, then executes it (using shell on remote)
#this is useful when you already have existing scripts to run on target servers(managed nodes)
#Go through ansible-doc for more info.
#End